import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserProvider } from './context/userContext'
import { ThemeProvider } from '@emotion/react'
import theme from './theme/theme'
import { CssBaseline } from '@mui/material'
import ClientLayout from './layout/clientLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider theme={theme}>
          <CssBaseline/>
          <UserProvider>{children}</UserProvider>
        </ThemeProvider> */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}
